services:
  - type: web
    name: mindsync-backend
    runtime: node
    plan: free
    rootDirectory: ./backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_VISION_API_KEY
        sync: false

databases:
  - name: mindsync-mongodb
    databaseName: mindsync
    plan: free
